// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: recruitment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_recruitment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_recruitment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HrId          int64                  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_recruitment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *CreateJobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	HrId          int64                  `protobuf:"varint,2,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"` // 用于校验岗位归属权限
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 1-上架, 0-下架
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_recruitment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *UpdateJobRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *UpdateJobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateJobRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListHRJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HrId          int64                  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHRJobsRequest) Reset() {
	*x = ListHRJobsRequest{}
	mi := &file_recruitment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHRJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHRJobsRequest) ProtoMessage() {}

func (x *ListHRJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHRJobsRequest.ProtoReflect.Descriptor instead.
func (*ListHRJobsRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{4}
}

func (x *ListHRJobsRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *ListHRJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListHRJobsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_recruitment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HrId          int64                  `protobuf:"varint,4,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 1-上架, 0-下架
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_recruitment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{6}
}

func (x *JobInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobInfo) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *JobInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_recruitment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealName         string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Phone            string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	HighestEducation string                 `protobuf:"bytes,4,opt,name=highest_education,json=highestEducation,proto3" json:"highest_education,omitempty"`
	University       string                 `protobuf:"bytes,5,opt,name=university,proto3" json:"university,omitempty"`
	Experience       string                 `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Skills           string                 `protobuf:"bytes,7,opt,name=skills,proto3" json:"skills,omitempty"`
	ResumeOssUrl     string                 `protobuf:"bytes,8,opt,name=resume_oss_url,json=resumeOssUrl,proto3" json:"resume_oss_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_recruitment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetProfileResponse) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *GetProfileResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetProfileResponse) GetHighestEducation() string {
	if x != nil {
		return x.HighestEducation
	}
	return ""
}

func (x *GetProfileResponse) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *GetProfileResponse) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *GetProfileResponse) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *GetProfileResponse) GetResumeOssUrl() string {
	if x != nil {
		return x.ResumeOssUrl
	}
	return ""
}

type UpdateProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealName         string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Phone            string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	HighestEducation string                 `protobuf:"bytes,4,opt,name=highest_education,json=highestEducation,proto3" json:"highest_education,omitempty"`
	University       string                 `protobuf:"bytes,5,opt,name=university,proto3" json:"university,omitempty"`
	Experience       string                 `protobuf:"bytes,6,opt,name=experience,proto3" json:"experience,omitempty"`
	Skills           string                 `protobuf:"bytes,7,opt,name=skills,proto3" json:"skills,omitempty"`
	ResumeOssUrl     string                 `protobuf:"bytes,8,opt,name=resume_oss_url,json=resumeOssUrl,proto3" json:"resume_oss_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_recruitment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateProfileRequest) GetHighestEducation() string {
	if x != nil {
		return x.HighestEducation
	}
	return ""
}

func (x *UpdateProfileRequest) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *UpdateProfileRequest) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *UpdateProfileRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *UpdateProfileRequest) GetResumeOssUrl() string {
	if x != nil {
		return x.ResumeOssUrl
	}
	return ""
}

type ApplyJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyJobRequest) Reset() {
	*x = ApplyJobRequest{}
	mi := &file_recruitment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyJobRequest) ProtoMessage() {}

func (x *ApplyJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyJobRequest.ProtoReflect.Descriptor instead.
func (*ApplyJobRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyJobRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type AIChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HrId          int64                  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatRequest) Reset() {
	*x = AIChatRequest{}
	mi := &file_recruitment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatRequest) ProtoMessage() {}

func (x *AIChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatRequest.ProtoReflect.Descriptor instead.
func (*AIChatRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{11}
}

func (x *AIChatRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

func (x *AIChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AIChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatResponse) Reset() {
	*x = AIChatResponse{}
	mi := &file_recruitment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatResponse) ProtoMessage() {}

func (x *AIChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatResponse.ProtoReflect.Descriptor instead.
func (*AIChatResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{12}
}

func (x *AIChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HrId          int64                  `protobuf:"varint,1,opt,name=hr_id,json=hrId,proto3" json:"hr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_recruitment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{13}
}

func (x *GetChatHistoryRequest) GetHrId() int64 {
	if x != nil {
		return x.HrId
	}
	return 0
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_recruitment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{14}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`                             // "user" 或 "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                       // 对话内容
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_recruitment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{15}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0-成功, 其他-失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_recruitment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{16}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationsRequest) Reset() {
	*x = GetApplicationsRequest{}
	mi := &file_recruitment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationsRequest) ProtoMessage() {}

func (x *GetApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{17}
}

func (x *GetApplicationsRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type ApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*CandidateProfile    `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationsResponse) Reset() {
	*x = ApplicationsResponse{}
	mi := &file_recruitment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationsResponse) ProtoMessage() {}

func (x *ApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{18}
}

func (x *ApplicationsResponse) GetProfiles() []*CandidateProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type CandidateProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RealName         string                 `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	Phone            string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	University       string                 `protobuf:"bytes,3,opt,name=university,proto3" json:"university,omitempty"`
	ResumeUrl        string                 `protobuf:"bytes,4,opt,name=resume_url,json=resumeUrl,proto3" json:"resume_url,omitempty"`
	HighestEducation string                 `protobuf:"bytes,5,opt,name=highest_education,json=highestEducation,proto3" json:"highest_education,omitempty"`
	Skills           string                 `protobuf:"bytes,6,opt,name=skills,proto3" json:"skills,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CandidateProfile) Reset() {
	*x = CandidateProfile{}
	mi := &file_recruitment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateProfile) ProtoMessage() {}

func (x *CandidateProfile) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateProfile.ProtoReflect.Descriptor instead.
func (*CandidateProfile) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{19}
}

func (x *CandidateProfile) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *CandidateProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CandidateProfile) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *CandidateProfile) GetResumeUrl() string {
	if x != nil {
		return x.ResumeUrl
	}
	return ""
}

func (x *CandidateProfile) GetHighestEducation() string {
	if x != nil {
		return x.HighestEducation
	}
	return ""
}

func (x *CandidateProfile) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_recruitment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{20}
}

// 简历上传请求（文件内容以字节流传输）
type UploadResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeRequest) Reset() {
	*x = UploadResumeRequest{}
	mi := &file_recruitment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeRequest) ProtoMessage() {}

func (x *UploadResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeRequest.ProtoReflect.Descriptor instead.
func (*UploadResumeRequest) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{21}
}

func (x *UploadResumeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadResumeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadResumeRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	OssUrl        string                 `protobuf:"bytes,3,opt,name=oss_url,json=ossUrl,proto3" json:"oss_url,omitempty"` // 返回OSS相对路径，如 resumes/user_1_resume.pdf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResumeResponse) Reset() {
	*x = UploadResumeResponse{}
	mi := &file_recruitment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResumeResponse) ProtoMessage() {}

func (x *UploadResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recruitment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResumeResponse.ProtoReflect.Descriptor instead.
func (*UploadResumeResponse) Descriptor() ([]byte, []int) {
	return file_recruitment_proto_rawDescGZIP(), []int{22}
}

func (x *UploadResumeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadResumeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadResumeResponse) GetOssUrl() string {
	if x != nil {
		return x.OssUrl
	}
	return ""
}

var File_recruitment_proto protoreflect.FileDescriptor

const file_recruitment_proto_rawDesc = "" +
	"\n" +
	"\x11recruitment.proto\x12\vrecruitment\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"R\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"_\n" +
	"\x10CreateJobRequest\x12\x13\n" +
	"\x05hr_id\x18\x01 \x01(\x03R\x04hrId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8e\x01\n" +
	"\x10UpdateJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x13\n" +
	"\x05hr_id\x18\x02 \x01(\x03R\x04hrId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"P\n" +
	"\x11ListHRJobsRequest\x12\x13\n" +
	"\x05hr_id\x18\x01 \x01(\x03R\x04hrId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"<\n" +
	"\x10ListJobsResponse\x12(\n" +
	"\x04jobs\x18\x01 \x03(\v2\x14.recruitment.JobInfoR\x04jobs\"~\n" +
	"\aJobInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x13\n" +
	"\x05hr_id\x18\x04 \x01(\x03R\x04hrId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x8b\x02\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12+\n" +
	"\x11highest_education\x18\x04 \x01(\tR\x10highestEducation\x12\x1e\n" +
	"\n" +
	"university\x18\x05 \x01(\tR\n" +
	"university\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\tR\n" +
	"experience\x12\x16\n" +
	"\x06skills\x18\a \x01(\tR\x06skills\x12$\n" +
	"\x0eresume_oss_url\x18\b \x01(\tR\fresumeOssUrl\"\x8d\x02\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12+\n" +
	"\x11highest_education\x18\x04 \x01(\tR\x10highestEducation\x12\x1e\n" +
	"\n" +
	"university\x18\x05 \x01(\tR\n" +
	"university\x12\x1e\n" +
	"\n" +
	"experience\x18\x06 \x01(\tR\n" +
	"experience\x12\x16\n" +
	"\x06skills\x18\a \x01(\tR\x06skills\x12$\n" +
	"\x0eresume_oss_url\x18\b \x01(\tR\fresumeOssUrl\"A\n" +
	"\x0fApplyJobRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\">\n" +
	"\rAIChatRequest\x12\x13\n" +
	"\x05hr_id\x18\x01 \x01(\x03R\x04hrId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x0eAIChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\",\n" +
	"\x15GetChatHistoryRequest\x12\x13\n" +
	"\x05hr_id\x18\x01 \x01(\x03R\x04hrId\"N\n" +
	"\x16GetChatHistoryResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.recruitment.ChatMessageR\bmessages\"Z\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"6\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"/\n" +
	"\x16GetApplicationsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"Q\n" +
	"\x14ApplicationsResponse\x129\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1d.recruitment.CandidateProfileR\bprofiles\"\xc9\x01\n" +
	"\x10CandidateProfile\x12\x1b\n" +
	"\treal_name\x18\x01 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1e\n" +
	"\n" +
	"university\x18\x03 \x01(\tR\n" +
	"university\x12\x1d\n" +
	"\n" +
	"resume_url\x18\x04 \x01(\tR\tresumeUrl\x12+\n" +
	"\x11highest_education\x18\x05 \x01(\tR\x10highestEducation\x12\x16\n" +
	"\x06skills\x18\x06 \x01(\tR\x06skills\"\a\n" +
	"\x05Empty\"d\n" +
	"\x13UploadResumeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"U\n" +
	"\x14UploadResumeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\aoss_url\x18\x03 \x01(\tR\x06ossUrl2\xb4\a\n" +
	"\x12RecruitmentService\x12>\n" +
	"\x05Login\x12\x19.recruitment.LoginRequest\x1a\x1a.recruitment.LoginResponse\x12G\n" +
	"\tCreateJob\x12\x1d.recruitment.CreateJobRequest\x1a\x1b.recruitment.CommonResponse\x12G\n" +
	"\tUpdateJob\x12\x1d.recruitment.UpdateJobRequest\x1a\x1b.recruitment.CommonResponse\x12K\n" +
	"\n" +
	"ListHRJobs\x12\x1e.recruitment.ListHRJobsRequest\x1a\x1d.recruitment.ListJobsResponse\x12\\\n" +
	"\x12GetJobApplications\x12#.recruitment.GetApplicationsRequest\x1a!.recruitment.ApplicationsResponse\x12M\n" +
	"\n" +
	"GetProfile\x12\x1e.recruitment.GetProfileRequest\x1a\x1f.recruitment.GetProfileResponse\x12O\n" +
	"\rUpdateProfile\x12!.recruitment.UpdateProfileRequest\x1a\x1b.recruitment.CommonResponse\x12C\n" +
	"\x0eListPublicJobs\x12\x12.recruitment.Empty\x1a\x1d.recruitment.ListJobsResponse\x12E\n" +
	"\bApplyJob\x12\x1c.recruitment.ApplyJobRequest\x1a\x1b.recruitment.CommonResponse\x12S\n" +
	"\fUploadResume\x12 .recruitment.UploadResumeRequest\x1a!.recruitment.UploadResumeResponse\x12E\n" +
	"\n" +
	"ChatWithAI\x12\x1a.recruitment.AIChatRequest\x1a\x1b.recruitment.AIChatResponse\x12Y\n" +
	"\x0eGetChatHistory\x12\".recruitment.GetChatHistoryRequest\x1a#.recruitment.GetChatHistoryResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_recruitment_proto_rawDescOnce sync.Once
	file_recruitment_proto_rawDescData []byte
)

func file_recruitment_proto_rawDescGZIP() []byte {
	file_recruitment_proto_rawDescOnce.Do(func() {
		file_recruitment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recruitment_proto_rawDesc), len(file_recruitment_proto_rawDesc)))
	})
	return file_recruitment_proto_rawDescData
}

var file_recruitment_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_recruitment_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: recruitment.LoginRequest
	(*LoginResponse)(nil),          // 1: recruitment.LoginResponse
	(*CreateJobRequest)(nil),       // 2: recruitment.CreateJobRequest
	(*UpdateJobRequest)(nil),       // 3: recruitment.UpdateJobRequest
	(*ListHRJobsRequest)(nil),      // 4: recruitment.ListHRJobsRequest
	(*ListJobsResponse)(nil),       // 5: recruitment.ListJobsResponse
	(*JobInfo)(nil),                // 6: recruitment.JobInfo
	(*GetProfileRequest)(nil),      // 7: recruitment.GetProfileRequest
	(*GetProfileResponse)(nil),     // 8: recruitment.GetProfileResponse
	(*UpdateProfileRequest)(nil),   // 9: recruitment.UpdateProfileRequest
	(*ApplyJobRequest)(nil),        // 10: recruitment.ApplyJobRequest
	(*AIChatRequest)(nil),          // 11: recruitment.AIChatRequest
	(*AIChatResponse)(nil),         // 12: recruitment.AIChatResponse
	(*GetChatHistoryRequest)(nil),  // 13: recruitment.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil), // 14: recruitment.GetChatHistoryResponse
	(*ChatMessage)(nil),            // 15: recruitment.ChatMessage
	(*CommonResponse)(nil),         // 16: recruitment.CommonResponse
	(*GetApplicationsRequest)(nil), // 17: recruitment.GetApplicationsRequest
	(*ApplicationsResponse)(nil),   // 18: recruitment.ApplicationsResponse
	(*CandidateProfile)(nil),       // 19: recruitment.CandidateProfile
	(*Empty)(nil),                  // 20: recruitment.Empty
	(*UploadResumeRequest)(nil),    // 21: recruitment.UploadResumeRequest
	(*UploadResumeResponse)(nil),   // 22: recruitment.UploadResumeResponse
}
var file_recruitment_proto_depIdxs = []int32{
	6,  // 0: recruitment.ListJobsResponse.jobs:type_name -> recruitment.JobInfo
	15, // 1: recruitment.GetChatHistoryResponse.messages:type_name -> recruitment.ChatMessage
	19, // 2: recruitment.ApplicationsResponse.profiles:type_name -> recruitment.CandidateProfile
	0,  // 3: recruitment.RecruitmentService.Login:input_type -> recruitment.LoginRequest
	2,  // 4: recruitment.RecruitmentService.CreateJob:input_type -> recruitment.CreateJobRequest
	3,  // 5: recruitment.RecruitmentService.UpdateJob:input_type -> recruitment.UpdateJobRequest
	4,  // 6: recruitment.RecruitmentService.ListHRJobs:input_type -> recruitment.ListHRJobsRequest
	17, // 7: recruitment.RecruitmentService.GetJobApplications:input_type -> recruitment.GetApplicationsRequest
	7,  // 8: recruitment.RecruitmentService.GetProfile:input_type -> recruitment.GetProfileRequest
	9,  // 9: recruitment.RecruitmentService.UpdateProfile:input_type -> recruitment.UpdateProfileRequest
	20, // 10: recruitment.RecruitmentService.ListPublicJobs:input_type -> recruitment.Empty
	10, // 11: recruitment.RecruitmentService.ApplyJob:input_type -> recruitment.ApplyJobRequest
	21, // 12: recruitment.RecruitmentService.UploadResume:input_type -> recruitment.UploadResumeRequest
	11, // 13: recruitment.RecruitmentService.ChatWithAI:input_type -> recruitment.AIChatRequest
	13, // 14: recruitment.RecruitmentService.GetChatHistory:input_type -> recruitment.GetChatHistoryRequest
	1,  // 15: recruitment.RecruitmentService.Login:output_type -> recruitment.LoginResponse
	16, // 16: recruitment.RecruitmentService.CreateJob:output_type -> recruitment.CommonResponse
	16, // 17: recruitment.RecruitmentService.UpdateJob:output_type -> recruitment.CommonResponse
	5,  // 18: recruitment.RecruitmentService.ListHRJobs:output_type -> recruitment.ListJobsResponse
	18, // 19: recruitment.RecruitmentService.GetJobApplications:output_type -> recruitment.ApplicationsResponse
	8,  // 20: recruitment.RecruitmentService.GetProfile:output_type -> recruitment.GetProfileResponse
	16, // 21: recruitment.RecruitmentService.UpdateProfile:output_type -> recruitment.CommonResponse
	5,  // 22: recruitment.RecruitmentService.ListPublicJobs:output_type -> recruitment.ListJobsResponse
	16, // 23: recruitment.RecruitmentService.ApplyJob:output_type -> recruitment.CommonResponse
	22, // 24: recruitment.RecruitmentService.UploadResume:output_type -> recruitment.UploadResumeResponse
	12, // 25: recruitment.RecruitmentService.ChatWithAI:output_type -> recruitment.AIChatResponse
	14, // 26: recruitment.RecruitmentService.GetChatHistory:output_type -> recruitment.GetChatHistoryResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_recruitment_proto_init() }
func file_recruitment_proto_init() {
	if File_recruitment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recruitment_proto_rawDesc), len(file_recruitment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recruitment_proto_goTypes,
		DependencyIndexes: file_recruitment_proto_depIdxs,
		MessageInfos:      file_recruitment_proto_msgTypes,
	}.Build()
	File_recruitment_proto = out.File
	file_recruitment_proto_goTypes = nil
	file_recruitment_proto_depIdxs = nil
}
