// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0--rc2
// source: recruitment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecruitmentService_Login_FullMethodName              = "/recruitment.RecruitmentService/Login"
	RecruitmentService_CreateJob_FullMethodName          = "/recruitment.RecruitmentService/CreateJob"
	RecruitmentService_UpdateJob_FullMethodName          = "/recruitment.RecruitmentService/UpdateJob"
	RecruitmentService_ListHRJobs_FullMethodName         = "/recruitment.RecruitmentService/ListHRJobs"
	RecruitmentService_GetJobApplications_FullMethodName = "/recruitment.RecruitmentService/GetJobApplications"
	RecruitmentService_GetProfile_FullMethodName         = "/recruitment.RecruitmentService/GetProfile"
	RecruitmentService_UpdateProfile_FullMethodName      = "/recruitment.RecruitmentService/UpdateProfile"
	RecruitmentService_ListPublicJobs_FullMethodName     = "/recruitment.RecruitmentService/ListPublicJobs"
	RecruitmentService_ApplyJob_FullMethodName           = "/recruitment.RecruitmentService/ApplyJob"
	RecruitmentService_UploadResume_FullMethodName       = "/recruitment.RecruitmentService/UploadResume"
	RecruitmentService_ChatWithAI_FullMethodName         = "/recruitment.RecruitmentService/ChatWithAI"
	RecruitmentService_GetChatHistory_FullMethodName     = "/recruitment.RecruitmentService/GetChatHistory"
)

// RecruitmentServiceClient is the client API for RecruitmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 招聘系统核心服务
type RecruitmentServiceClient interface {
	// --- 账号与权限 ---
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// --- HR 管理端功能 ---
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	ListHRJobs(ctx context.Context, in *ListHRJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	GetJobApplications(ctx context.Context, in *GetApplicationsRequest, opts ...grpc.CallOption) (*ApplicationsResponse, error)
	// --- 候选人端功能 ---
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	ListPublicJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListJobsResponse, error)
	ApplyJob(ctx context.Context, in *ApplyJobRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	UploadResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*UploadResumeResponse, error)
	// --- AI 助手功能 ---
	ChatWithAI(ctx context.Context, in *AIChatRequest, opts ...grpc.CallOption) (*AIChatResponse, error)
	GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error)
}

type recruitmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecruitmentServiceClient(cc grpc.ClientConnInterface) RecruitmentServiceClient {
	return &recruitmentServiceClient{cc}
}

func (c *recruitmentServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_UpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) ListHRJobs(ctx context.Context, in *ListHRJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_ListHRJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) GetJobApplications(ctx context.Context, in *GetApplicationsRequest, opts ...grpc.CallOption) (*ApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationsResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_GetJobApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) ListPublicJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_ListPublicJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) ApplyJob(ctx context.Context, in *ApplyJobRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_ApplyJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) UploadResume(ctx context.Context, in *UploadResumeRequest, opts ...grpc.CallOption) (*UploadResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResumeResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_UploadResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) ChatWithAI(ctx context.Context, in *AIChatRequest, opts ...grpc.CallOption) (*AIChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIChatResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_ChatWithAI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recruitmentServiceClient) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatHistoryResponse)
	err := c.cc.Invoke(ctx, RecruitmentService_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecruitmentServiceServer is the server API for RecruitmentService service.
// All implementations must embed UnimplementedRecruitmentServiceServer
// for forward compatibility.
//
// 招聘系统核心服务
type RecruitmentServiceServer interface {
	// --- 账号与权限 ---
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// --- HR 管理端功能 ---
	CreateJob(context.Context, *CreateJobRequest) (*CommonResponse, error)
	UpdateJob(context.Context, *UpdateJobRequest) (*CommonResponse, error)
	ListHRJobs(context.Context, *ListHRJobsRequest) (*ListJobsResponse, error)
	GetJobApplications(context.Context, *GetApplicationsRequest) (*ApplicationsResponse, error)
	// --- 候选人端功能 ---
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*CommonResponse, error)
	ListPublicJobs(context.Context, *Empty) (*ListJobsResponse, error)
	ApplyJob(context.Context, *ApplyJobRequest) (*CommonResponse, error)
	UploadResume(context.Context, *UploadResumeRequest) (*UploadResumeResponse, error)
	// --- AI 助手功能 ---
	ChatWithAI(context.Context, *AIChatRequest) (*AIChatResponse, error)
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error)
	mustEmbedUnimplementedRecruitmentServiceServer()
}

// UnimplementedRecruitmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecruitmentServiceServer struct{}

func (UnimplementedRecruitmentServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedRecruitmentServiceServer) CreateJob(context.Context, *CreateJobRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedRecruitmentServiceServer) UpdateJob(context.Context, *UpdateJobRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedRecruitmentServiceServer) ListHRJobs(context.Context, *ListHRJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHRJobs not implemented")
}
func (UnimplementedRecruitmentServiceServer) GetJobApplications(context.Context, *GetApplicationsRequest) (*ApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobApplications not implemented")
}
func (UnimplementedRecruitmentServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedRecruitmentServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedRecruitmentServiceServer) ListPublicJobs(context.Context, *Empty) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicJobs not implemented")
}
func (UnimplementedRecruitmentServiceServer) ApplyJob(context.Context, *ApplyJobRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyJob not implemented")
}
func (UnimplementedRecruitmentServiceServer) UploadResume(context.Context, *UploadResumeRequest) (*UploadResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadResume not implemented")
}
func (UnimplementedRecruitmentServiceServer) ChatWithAI(context.Context, *AIChatRequest) (*AIChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatWithAI not implemented")
}
func (UnimplementedRecruitmentServiceServer) GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedRecruitmentServiceServer) mustEmbedUnimplementedRecruitmentServiceServer() {}
func (UnimplementedRecruitmentServiceServer) testEmbeddedByValue()                            {}

// UnsafeRecruitmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecruitmentServiceServer will
// result in compilation errors.
type UnsafeRecruitmentServiceServer interface {
	mustEmbedUnimplementedRecruitmentServiceServer()
}

func RegisterRecruitmentServiceServer(s grpc.ServiceRegistrar, srv RecruitmentServiceServer) {
	// If the following call panics, it indicates UnimplementedRecruitmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecruitmentService_ServiceDesc, srv)
}

func _RecruitmentService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_UpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).UpdateJob(ctx, req.(*UpdateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_ListHRJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHRJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).ListHRJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_ListHRJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).ListHRJobs(ctx, req.(*ListHRJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_GetJobApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).GetJobApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_GetJobApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).GetJobApplications(ctx, req.(*GetApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_ListPublicJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).ListPublicJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_ListPublicJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).ListPublicJobs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_ApplyJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).ApplyJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_ApplyJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).ApplyJob(ctx, req.(*ApplyJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_UploadResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).UploadResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_UploadResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).UploadResume(ctx, req.(*UploadResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_ChatWithAI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).ChatWithAI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_ChatWithAI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).ChatWithAI(ctx, req.(*AIChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecruitmentService_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecruitmentServiceServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecruitmentService_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecruitmentServiceServer).GetChatHistory(ctx, req.(*GetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecruitmentService_ServiceDesc is the grpc.ServiceDesc for RecruitmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecruitmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recruitment.RecruitmentService",
	HandlerType: (*RecruitmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _RecruitmentService_Login_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _RecruitmentService_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _RecruitmentService_UpdateJob_Handler,
		},
		{
			MethodName: "ListHRJobs",
			Handler:    _RecruitmentService_ListHRJobs_Handler,
		},
		{
			MethodName: "GetJobApplications",
			Handler:    _RecruitmentService_GetJobApplications_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _RecruitmentService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _RecruitmentService_UpdateProfile_Handler,
		},
		{
			MethodName: "ListPublicJobs",
			Handler:    _RecruitmentService_ListPublicJobs_Handler,
		},
		{
			MethodName: "ApplyJob",
			Handler:    _RecruitmentService_ApplyJob_Handler,
		},
		{
			MethodName: "UploadResume",
			Handler:    _RecruitmentService_UploadResume_Handler,
		},
		{
			MethodName: "ChatWithAI",
			Handler:    _RecruitmentService_ChatWithAI_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _RecruitmentService_GetChatHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recruitment.proto",
}
